// Code generated by client-gen. DO NOT EDIT.

package v1beta1

type CDIExpansion interface{}

type CDIConfigExpansion interface{}

type DataImportCronExpansion interface{}

type DataSourceExpansion interface{}

type DataVolumeExpansion interface{}

type ObjectTransferExpansion interface{}

type StorageProfileExpansion interface{}

type VolumeCloneSourceExpansion interface{}

type VolumeImportSourceExpansion interface{}

type VolumeUploadSourceExpansion interface{}
