// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1beta1 "github.com/mabhi/containerized-data-importer-client-gen/versioned/typed/core/v1beta1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeCdiV1beta1 struct {
	*testing.Fake
}

func (c *FakeCdiV1beta1) CDIs() v1beta1.CDIInterface {
	return &FakeCDIs{c}
}

func (c *FakeCdiV1beta1) CDIConfigs() v1beta1.CDIConfigInterface {
	return &FakeCDIConfigs{c}
}

func (c *FakeCdiV1beta1) DataImportCrons(namespace string) v1beta1.DataImportCronInterface {
	return &FakeDataImportCrons{c, namespace}
}

func (c *FakeCdiV1beta1) DataSources(namespace string) v1beta1.DataSourceInterface {
	return &FakeDataSources{c, namespace}
}

func (c *FakeCdiV1beta1) DataVolumes(namespace string) v1beta1.DataVolumeInterface {
	return &FakeDataVolumes{c, namespace}
}

func (c *FakeCdiV1beta1) ObjectTransfers() v1beta1.ObjectTransferInterface {
	return &FakeObjectTransfers{c}
}

func (c *FakeCdiV1beta1) StorageProfiles() v1beta1.StorageProfileInterface {
	return &FakeStorageProfiles{c}
}

func (c *FakeCdiV1beta1) VolumeCloneSources(namespace string) v1beta1.VolumeCloneSourceInterface {
	return &FakeVolumeCloneSources{c, namespace}
}

func (c *FakeCdiV1beta1) VolumeImportSources(namespace string) v1beta1.VolumeImportSourceInterface {
	return &FakeVolumeImportSources{c, namespace}
}

func (c *FakeCdiV1beta1) VolumeUploadSources(namespace string) v1beta1.VolumeUploadSourceInterface {
	return &FakeVolumeUploadSources{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeCdiV1beta1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
